export const products = [
  {
    id: "qnexus-control",
    icon: "fa-network-wired",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QNexus Control",
    description: "Plataforma integral de control logístico y gestión de flotas vehiculares en tiempo real.",
    route: "/productos/qnexus-control",
  },
  {
    id: "qcampus-one",
    icon: "fa-graduation-cap",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QCampusOne",
    description: "Sistema completo de gestión académica y administrativa para instituciones educativas.",
    route: "/productos/qcampus-one",
  },
  {
    id: "qnexus-app",
    icon: "fa-mobile-alt",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QNexus App",
    description: "Aplicación móvil para monitoreo y control operativo desde cualquier lugar.",
    route: "/productos/qnexus-app",
  },
  {
    id: "holakura",
    icon: "fa-comments",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "HolaKura",
    description: "Plataforma de atención al cliente con inteligencia artificial conversacional.",
    route: "/productos/holakura",
  },
  {
    id: "auranuba",
    icon: "fa-calendar-check",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "Auranuba",
    description: "Sistema inteligente de gestión de eventos y experiencias personalizadas.",
    route: "/productos/auranuba",
  },
];

export const customSoftware = {
  id: "custom-software",
  icon: "fa-code",
  iconColor: "text-[#575757]",
  iconBg: "bg-[#575757]/10",
  title: "Software a la Medida",
  description: "Desarrollo de soluciones personalizadas que se adaptan exactamente a los procesos únicos de tu empresa, integrando tecnologías modernas para maximizar la eficiencia operativa.",
};
