export const products = [
  {
    id: "qnexus-control",
    icon: "fa-network-wired",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QNexus Control",
    description: "Gestión integral de flotas vehiculares y cotizaciones con rastreo en tiempo real.",
    route: "/productos/qnexus-control.html",
  },
  {
    id: "qcampus-one",
    icon: "fa-graduation-cap",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QCampusOne",
    description: "Control escolar completo con gestión de finanzas para instituciones educativas.",
    route: "/productos/qcampus-one.html",
  },
  {
    id: "qnexus-app",
    icon: "fa-mobile-alt",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "QNexus App",
    description: "Movilidad y rastreo en tiempo real desde cualquier dispositivo móvil.",
    route: "/productos/qnexus-app.html",
  },
  {
    id: "holakura",
    icon: "fa-notes-medical",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "HolaKura",
    description: "Expedientes clínicos digitales y agenda inteligente para médicos y consultorios.",
    route: "/productos/holakura.html",
  },
  {
    id: "auranuba",
    icon: "fa-envelope-open-text",
    iconColor: "text-[#575757]",
    iconBg: "bg-[#575757]/10",
    title: "Auranuba",
    description: "Invitaciones digitales y confirmación de asistencia para eventos.",
    route: "/productos/auranuba.html",
  },
];

export const customSoftware = {
  id: "custom-software",
  icon: "fa-code",
  iconColor: "text-[#575757]",
  iconBg: "bg-[#575757]/10",
  title: "Software a la Medida",
  description: "Desarrollo de soluciones personalizadas que se adaptan exactamente a los procesos únicos de tu empresa, integrando tecnologías modernas para maximizar la eficiencia operativa.",
};
